---
title: "UIUC, STAT 420, 2018 Summer, Data Analysis Project Proposal, Assessing Developments in the Search for Another Earth"
author: "Jerome JASINSKI (jeromej2@illinois.edu), Dongrong LI (dl12@illinois.edu), Thai Duy Cuong NGUYEN (thaidn2@illinois.edu)"
date: '2018-07-17'
output:
  html_document: 
    toc: yes
  pdf_document: default
urlcolor: cyan
---

## Dataset Description ##

---
Description of the dataset. You do not necessarily have to list all the variables, but at least mention those of greatest importance.
After reading the proposal, a reader should have a good understanding of your dataset without needing to reference the data itself or other documentation.
---

The raw data we will be using for our Data Analysis Project consists of 354 attributes for 3,748 confirmed exoplanets and their host stars as well as information about their discovery as of 2018 July 5. Discovery information includes the method used to detect the exoplanet, the locale of the observatories used for detection (i.e., whether ground-based, space-based, or a mixture of both observations were used for detection), and the year of discovery. Physical characteristics of exoplanets present in the archive include planetary mass, orbital period, and orbital semi-major axis. Physical properties of host stars listed in the archive include stellar mass, stellar radius, effective temperature, surface gravity, spectral type, luminosity, and distance from Earth. These physical properties for both exoplanets and their host stars are important for determining the similarity between an exoplanet and Earth, and their detection sensitivity.

## Dataset Background ##

---
Background information on the dataset, including specific citation of its source.
---

The dataset we will be using for our Data Analysis Project is derived from the NASA Exoplanet Archive, which can be found at the following URL [https://exoplanetarchive.ipac.caltech.edu](https://exoplanetarchive.ipac.caltech.edu). This archive is an online compilation, collation, and cross-correlation of astronomical data and information on exoplanets and their host stars. The data are vetted by a team of astronomers at the California Institute of Technology (Caltech) under contract with the National Aeronautics and Space Administration (NASA) under the Exoplanet Exploration Program. An extensive overview of the data, services and tools of the archive can be found in a published paper by Akeson, et al. (2013, PASP, 125, 989) in the Publications of the Astronomical Society of the Pacific (PASP). This publication can be found [here](http://adsabs.harvard.edu/abs/2013PASP..125..989A).

## Statement of Interest ##

---
A brief statement of the business, science, research, or personal interest you have in the dataset that you hope to explore.
---

Are we alone in the Universe? This is one of the most profound questions that humankind has sought to answer since the beginning of recorded history. We can gain some insight into this mystery with the modern search for exoplanets. The underlying purpose of contemporary exoplanet programs is to discover habitable planets, especially around nearby stars, and find evidence of life elsewhere in the cosmos. Using Earth and its lifeforms as a template to assess habitility, we seek other celestial bodies with conditions similar to our own, i.e., with Earth-like surface gravities and temperatures capable to sustaining liquid water. In order to meet these criteria, most habitable worlds must be a particular mass and a particular distance from their host star. We are constantly trying to improve our detection sensitivity through advancements in technology and methods. It is the measurement of these developments that interest us for this Data Analysis Project.

## Using `R` ##

---
Evidence that the data can be loaded into `R`. Load the data, and print the first few values of the response variable as evidence.
---

We have trimmed the original dataset from the NASA Exoplanet Archive to 37 attributes that are most relevant and directly related to habitable planets. These data are stored in the file `planets_lite.csv`. The variables for which we are interested as responses are `pl_bmasse`, `pl_orbsmax` and `st_dist` are the planet mass in Earth masses ($R_\odot = 5.9722 \times 10^{24}\,\rm{kg}$), the planet orbital semi-major axis in astronomical units ($\rm{AU} = 1.495978707 \times 10^{11}\,\rm{m}$), and the distance from our solar system to the exoplanet system in parsecs ($\rm{pc} = 3.0857 \times 10^{16}\,\rm{m}$). These response variables are key physical parameters that determine the habitability of a planet.

The first few values of the response variables of interest are provided below.

```{r}
planets = read.csv("planets_lite.csv")
head(planets$pl_bmasse[complete.cases(planets$pl_bmasse)])
head(planets$pl_orbsmax[complete.cases(planets$pl_orbsmax)])
head(planets$st_dist[complete.cases(planets$st_dist)])
```
